name: Update Dependency Graph

on:
  push:
    branches:
      - main

jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@72bdd87d620be905d2add3aa48214250a1921eb3